refactor: rename ctnr namespace to containers
open-space-collective/open-space-toolkit-core pull request #142
Opened 2024-01-12 19:31 UTC by kyle-cochran

Plural "containers" rather than singular "container" to be consistent with the Python bindings.

2024-01-12 20:43 UTC, vishwa2710 requested changes
IMO this should be `container`

2024-01-15 08:32 UTC, apaletta3 submitted a review, later dismissed
Agreed with vishwa, `container` is better

2024-01-23 08:51 UTC, vishwa2710 approved these changes

2024-01-23 16:04 UTC, apaletta3 approved these changes

2024-01-23 18:59 UTC, merged